// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.6.1
// source: liars_network.proto

package liars_network

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// LieServiceClient is the client API for LieService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LieServiceClient interface {
	LieQuery(ctx context.Context, in *LieRequest, opts ...grpc.CallOption) (*LieResponse, error)
}

type lieServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLieServiceClient(cc grpc.ClientConnInterface) LieServiceClient {
	return &lieServiceClient{cc}
}

func (c *lieServiceClient) LieQuery(ctx context.Context, in *LieRequest, opts ...grpc.CallOption) (*LieResponse, error) {
	out := new(LieResponse)
	err := c.cc.Invoke(ctx, "/liars_network.LieService/LieQuery", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LieServiceServer is the server API for LieService service.
// All implementations must embed UnimplementedLieServiceServer
// for forward compatibility
type LieServiceServer interface {
	LieQuery(context.Context, *LieRequest) (*LieResponse, error)
	mustEmbedUnimplementedLieServiceServer()
}

// UnimplementedLieServiceServer must be embedded to have forward compatible implementations.
type UnimplementedLieServiceServer struct {
}

func (UnimplementedLieServiceServer) LieQuery(context.Context, *LieRequest) (*LieResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LieQuery not implemented")
}
func (UnimplementedLieServiceServer) mustEmbedUnimplementedLieServiceServer() {}

// UnsafeLieServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LieServiceServer will
// result in compilation errors.
type UnsafeLieServiceServer interface {
	mustEmbedUnimplementedLieServiceServer()
}

func RegisterLieServiceServer(s grpc.ServiceRegistrar, srv LieServiceServer) {
	s.RegisterService(&LieService_ServiceDesc, srv)
}

func _LieService_LieQuery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LieRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LieServiceServer).LieQuery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/liars_network.LieService/LieQuery",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LieServiceServer).LieQuery(ctx, req.(*LieRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LieService_ServiceDesc is the grpc.ServiceDesc for LieService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LieService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "liars_network.LieService",
	HandlerType: (*LieServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LieQuery",
			Handler:    _LieService_LieQuery_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "liars_network.proto",
}
