// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.6.1
// source: liars_network.proto

package liars_network

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LieRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// if true, then this request is sent from playexpert command.
	ExpertMode    bool     `protobuf:"varint,1,opt,name=expert_mode,json=expertMode,proto3" json:"expert_mode,omitempty"`
	OtherAgentIds []string `protobuf:"bytes,2,rep,name=other_agent_ids,json=otherAgentIds,proto3" json:"other_agent_ids,omitempty"`
}

func (x *LieRequest) Reset() {
	*x = LieRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_liars_network_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LieRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LieRequest) ProtoMessage() {}

func (x *LieRequest) ProtoReflect() protoreflect.Message {
	mi := &file_liars_network_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LieRequest.ProtoReflect.Descriptor instead.
func (*LieRequest) Descriptor() ([]byte, []int) {
	return file_liars_network_proto_rawDescGZIP(), []int{0}
}

func (x *LieRequest) GetExpertMode() bool {
	if x != nil {
		return x.ExpertMode
	}
	return false
}

func (x *LieRequest) GetOtherAgentIds() []string {
	if x != nil {
		return x.OtherAgentIds
	}
	return nil
}

type LieResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AgentValue           int32   `protobuf:"varint,1,opt,name=agent_value,json=agentValue,proto3" json:"agent_value,omitempty"`
	CollectedAgentValues []int32 `protobuf:"varint,2,rep,packed,name=collected_agent_values,json=collectedAgentValues,proto3" json:"collected_agent_values,omitempty"`
}

func (x *LieResponse) Reset() {
	*x = LieResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_liars_network_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LieResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LieResponse) ProtoMessage() {}

func (x *LieResponse) ProtoReflect() protoreflect.Message {
	mi := &file_liars_network_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LieResponse.ProtoReflect.Descriptor instead.
func (*LieResponse) Descriptor() ([]byte, []int) {
	return file_liars_network_proto_rawDescGZIP(), []int{1}
}

func (x *LieResponse) GetAgentValue() int32 {
	if x != nil {
		return x.AgentValue
	}
	return 0
}

func (x *LieResponse) GetCollectedAgentValues() []int32 {
	if x != nil {
		return x.CollectedAgentValues
	}
	return nil
}

var File_liars_network_proto protoreflect.FileDescriptor

var file_liars_network_proto_rawDesc = []byte{
	0x0a, 0x13, 0x6c, 0x69, 0x61, 0x72, 0x73, 0x5f, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x6c, 0x69, 0x61, 0x72, 0x73, 0x5f, 0x6e, 0x65, 0x74,
	0x77, 0x6f, 0x72, 0x6b, 0x22, 0x55, 0x0a, 0x0a, 0x4c, 0x69, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x65, 0x78, 0x70, 0x65, 0x72, 0x74, 0x5f, 0x6d, 0x6f, 0x64,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x65, 0x78, 0x70, 0x65, 0x72, 0x74, 0x4d,
	0x6f, 0x64, 0x65, 0x12, 0x26, 0x0a, 0x0f, 0x6f, 0x74, 0x68, 0x65, 0x72, 0x5f, 0x61, 0x67, 0x65,
	0x6e, 0x74, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0d, 0x6f, 0x74,
	0x68, 0x65, 0x72, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x73, 0x22, 0x64, 0x0a, 0x0b, 0x4c,
	0x69, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x61, 0x67,
	0x65, 0x6e, 0x74, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0a, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x34, 0x0a, 0x16, 0x63,
	0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x5f, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x05, 0x52, 0x14, 0x63, 0x6f, 0x6c,
	0x6c, 0x65, 0x63, 0x74, 0x65, 0x64, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x73, 0x32, 0x51, 0x0a, 0x0a, 0x4c, 0x69, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x43, 0x0a, 0x08, 0x4c, 0x69, 0x65, 0x51, 0x75, 0x65, 0x72, 0x79, 0x12, 0x19, 0x2e, 0x6c, 0x69,
	0x61, 0x72, 0x73, 0x5f, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2e, 0x4c, 0x69, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x6c, 0x69, 0x61, 0x72, 0x73, 0x5f, 0x6e,
	0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2e, 0x4c, 0x69, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x42, 0x1f, 0x5a, 0x1d, 0x2e, 0x2f, 0x6c, 0x69, 0x61, 0x72, 0x73, 0x5f,
	0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x3b, 0x6c, 0x69, 0x61, 0x72, 0x73, 0x5f, 0x6e, 0x65,
	0x74, 0x77, 0x6f, 0x72, 0x6b, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_liars_network_proto_rawDescOnce sync.Once
	file_liars_network_proto_rawDescData = file_liars_network_proto_rawDesc
)

func file_liars_network_proto_rawDescGZIP() []byte {
	file_liars_network_proto_rawDescOnce.Do(func() {
		file_liars_network_proto_rawDescData = protoimpl.X.CompressGZIP(file_liars_network_proto_rawDescData)
	})
	return file_liars_network_proto_rawDescData
}

var file_liars_network_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_liars_network_proto_goTypes = []interface{}{
	(*LieRequest)(nil),  // 0: liars_network.LieRequest
	(*LieResponse)(nil), // 1: liars_network.LieResponse
}
var file_liars_network_proto_depIdxs = []int32{
	0, // 0: liars_network.LieService.LieQuery:input_type -> liars_network.LieRequest
	1, // 1: liars_network.LieService.LieQuery:output_type -> liars_network.LieResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_liars_network_proto_init() }
func file_liars_network_proto_init() {
	if File_liars_network_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_liars_network_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LieRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_liars_network_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LieResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_liars_network_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_liars_network_proto_goTypes,
		DependencyIndexes: file_liars_network_proto_depIdxs,
		MessageInfos:      file_liars_network_proto_msgTypes,
	}.Build()
	File_liars_network_proto = out.File
	file_liars_network_proto_rawDesc = nil
	file_liars_network_proto_goTypes = nil
	file_liars_network_proto_depIdxs = nil
}
